[2023-12-22T14:53:50.448+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2023-12-15T00:00:00+00:00 [queued]>
[2023-12-22T14:53:50.884+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2023-12-15T00:00:00+00:00 [queued]>
[2023-12-22T14:53:50.896+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-22T14:53:51.616+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-12-15 00:00:00+00:00
[2023-12-22T14:53:51.667+0000] {standard_task_runner.py:60} INFO - Started process 58480 to run task
[2023-12-22T14:53:51.689+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2023-12-15T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpei46fllv']
[2023-12-22T14:53:51.735+0000] {standard_task_runner.py:88} INFO - Job 246: Subtask postgres_to_s3
[2023-12-22T14:53:52.193+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2023-12-15T00:00:00+00:00 [running]> on host dd88aaafc1d9
[2023-12-22T14:53:53.070+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarwar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v02' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-15T00:00:00+00:00'
[2023-12-22T14:53:53.119+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2023-12-22T14:53:53.183+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T14:53:53.233+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 19, in postgres_to_s3
    cursor.execute("select * from public.orders where date >= %s and date <= %s", ds_nodash, next_ds_nodash)
TypeError: function takes at most 2 arguments (3 given)
[2023-12-22T14:53:53.309+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20231215T000000, start_date=20231222T145350, end_date=20231222T145353
[2023-12-22T14:53:53.626+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 246 for task postgres_to_s3 (function takes at most 2 arguments (3 given); 58480)
[2023-12-22T14:53:53.707+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-22T14:53:53.803+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-22T15:03:40.489+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2023-12-15T00:00:00+00:00 [queued]>
[2023-12-22T15:03:40.604+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2023-12-15T00:00:00+00:00 [queued]>
[2023-12-22T15:03:40.626+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-22T15:03:40.833+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-12-15 00:00:00+00:00
[2023-12-22T15:03:40.898+0000] {standard_task_runner.py:60} INFO - Started process 59427 to run task
[2023-12-22T15:03:40.915+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2023-12-15T00:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpmt04_q9z']
[2023-12-22T15:03:41.092+0000] {standard_task_runner.py:88} INFO - Job 267: Subtask postgres_to_s3
[2023-12-22T15:03:41.656+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2023-12-15T00:00:00+00:00 [running]> on host dd88aaafc1d9
[2023-12-22T15:03:42.388+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarwar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v02' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-15T00:00:00+00:00'
[2023-12-22T15:03:42.501+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2023-12-22T15:03:42.652+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T15:03:42.711+0000] {dag_with_postgres_hooks.py:26} INFO - Saved orders in file: dags/get_orders_20231215.txt
[2023-12-22T15:03:42.714+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-22T15:03:42.789+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20231215T000000, start_date=20231222T150340, end_date=20231222T150342
[2023-12-22T15:03:43.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-22T15:03:43.386+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
